// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfvyzrpcputsbpvixrkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdnl6cnBjcHV0c2Jwdml4cmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzE1MjQsImV4cCI6MjA1OTM0NzUyNH0.kQMWV9utvmlzkKl7jji8XhwGQjzMUokZORU2RZqxRIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);